spring.application.name=notification-service
server.port=8086
spring.jpa.hibernate.ddl-auto=update 
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=bharattrains
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khandetushar2001@gmail.com
spring.mail.password=iusvjbklnysldpit
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=train-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer