spring.application.name=api-gateway
server.port=8089

# TRAIN SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=train-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/trains/**

# BOOKING SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=booking-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/bookings/**

# SEAT SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=seat-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/seats/**

# PAYMENT SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=payment-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/payments/**

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=user-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/users/**,/auth/**

# NOTIFICATION SERVICE
spring.cloud.gateway.server.webflux.routes[5].id=notification-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/notifications/**


# GLOBAL CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*